client/app/globals.css, client/app/page.tsx
=> style: add the border animation of the homepage

client/app/globals.css, client/app/page.tsx
=> style: tweak the homepage

client/app/page.tsx, client/components/User.tsx, server/auth/router.py, server/main.py
=> fix: login

server/auth/get_user_info.py, server/auth/router.py
=> fix: auth info

client/package.json, client/yarn.lock, lui/ README.md, lui/package.json, lui/src/Chat/index.tsx, server/agent/base.py
* agent 消息体容错处理
* assistant 消息体 format
close #312
=> fix: solve the tool result

.github/workflows/pr-tests.yml, .gitignore
=> feat: 雕一下 codecov 的花

README.en-US.md, README.md
=> feat: add codecov badge

assistant/package.json, assistant/src/Chat/index.tsx, assistant/src/style.css, assistant/src/utils/chatTranslator.ts
=> Provide corresponding copy when there is an error in the dialogue request.

server/event_handler/discussion.py, server/event_handler/issue.py, server/github_app/handlers.py, server/github_app/router.py
=> fix: fix the discuession

server/agent/bot/bot_builder.py, server/agent/prompts/bot_builder.py
=> fix: bot builder

.github/workflows/pr-tests.yml, docker/Dockerfile.aws.lambda, server/aws/router.py, server/requirements.txt
=> feat: revert upload detect

client/app/page.tsx
继续调优首页样式，包含响应式优化（最小 900px 和工作台保持一致）、Lottie 动画替换、案例视频自动播放及大屏的首页 action 适配（没有滚动条时自动出现 action）
=> refactor: imporve homepage detials

template.yml
=> fix: passing SQS_QUEUE_URL

assistant/package.json, assistant/src/Chat/index.tsx, assistant/src/services/ChatController.ts, migrations/supabase/migrations/20240905155017_remote_schema.sql, server/auth/middleware.py, server/core/models/bot.py
=> feat: support 3rd auth

client/app/page.tsx
=> feat: ssr for homepage stars

server/agent/prompts/bot_template.py, server/agent/prompts/issue_helper.py, server/agent/qa_chat.py, server/event_handler/issue.py
=> fix: tewak the promt of the issue helper

docker/Dockerfile.aws.lambda
- 更新 label，以使用 GitHub 的官方 packages 库
=> chore: update docker label

server/bot/router.py
=> chore: prohibit manually publishing the bot through the API

assistant/src/Assistant/index.md, server/agent/base.py, server/agent/llm/clients/openai.py
=> feat: track token usage when stream chat

README.ja-JP.md, README.md
I created Japanese translated README.
=> docs: add Japanese README

server/agent/bot/get_bot.py, server/chat/router.py
=> feat: add more log

migrations/supabase/migrations/20240912023152_remote_schema.sql, server/core/dao/userTokenUsageDAO.py, server/core/models/user_token_usage.py, server/core/service/user_token_usage.py, server/user/router.py
=> feat: add token usage facade

client/app/page.tsx, client/components/GitHubStars.tsx, client/components/LangSwitcher.tsx
Fetch Data in a Server Component
=> fix: solve the stars number

migrations/supabase/migrations/20240913114522_remote_schema.sql
=> chore: upload supabase migration

server/github_app/purchased.py, server/github_app/router.py
=> feat: support-purchased

server/event_handler/issue.py
=> fix: fix issue comment

server/core/dao/authorizationDAO.py, server/core/dao/repositoryConfigDAO.py, server/core/models/authorization.py, server/core/models/repository.py, server/github_app/router.py
=> fix: installation callback logic

.github/workflows/pr-tests.yml, server/auth/cors_middleware.py, server/auth/middleware.py, server/main.py, server/tests/auth/test_middleware.py, server/tests/test_main.py, template.yml
=> feat: allow anouymouse cors by token

server/agent/prompts/issue_helper.py, server/agent/qa_chat.py, server/agent/tools/issue.py, server/agent/tools/pull_request.py, server/agent/tools/sourcecode.py
- 优化 issue 回复逻辑
- 现在大概会这么回：
```
analysis_result=你可以尝试修改 `/usr/lib/node_modules/fanyi/bin/fanyi.js` 的 shebang 行，将 `--no-deprecation` 参数移到脚本内部处理。具体修改如下：
```diff
- #!/usr/bin/env -S node --no-deprecation
+ #!/usr/bin/env node
const { Command } = require('commander');
const chalk = require('chalk');
const updateNotifier = require('update-notifier');
const pkg = require('../package.json');
const config = require('../lib/config');
const { searchList } = require('../lib/searchHistory');
// 添加以下代码以禁用弃用警告
process.noDeprecation = true;
updateNotifier({ pkg }).notify();
const program = new Command();
program
.name(pkg.name)
.description(pkg.description)
.version(pkg.version)
.action(() => {
// 你的代码
});
program
.command('config')
.description('配置')
.action(async () => {
const options = await …
=> feat: optimize issue resolver logic

server/README.zh-CN.md, server/agent/prompts/issue_helper.py, server/event_handler/discussion.py, server/event_handler/issue.py, server/tests/fixtures/github/events/discussion/comment.json
=> fix: change name from petercat-bot to petercat-assistant

client/app/factory/edit/page.tsx, client/app/page.tsx
=> fix: tweak the style for the multi-language

server/bot/builder.py
=> fix: add default value of llm field

server/agent/prompts/pull_request.py
=> chore: tweak the prompt of the pull request

client/app/contexts/BotContext.tsx
=> fix: remove the default token_id

server/README.zh-CN.md, server/github_app/router.py
github 接口变化，owner_id 不再是 string 类型，需要修改成 string 类型。
fix issue：https://github.com/petercat-ai/petercat/issues/458
=> fix(install): stringify owner_id

assistant/src/services/UserController.ts
=> fix: remove apiDomain var in assistant package

client/app/factory/edit/page.tsx
=> fix(ci): fix build error

server/agent/bot/__init__.py, server/agent/llm/__init__.py, server/agent/llm/base.py, server/agent/llm/clients/gemini.py, server/agent/llm/clients/openai.py, server/bot/builder.py, server/core/models/bot.py
=> feat: support config temperature in bot

client/app/page.tsx
=> refactor: improve mobile styles

client/app/factory/edit/page.tsx, server/requirements.txt, server/setup_python.sh
* 修复接收用户协议样式
* 增加用户协议多语言适配
close #543 #539
=> fix: resolve the infinite redirect issue on the edit page

client/.kiwi/en/app.ts, client/.kiwi/en/index.ts, client/.kiwi/en/release.ts, client/.kiwi/ja/app.ts, client/.kiwi/ja/index.ts, client/.kiwi/ja/release.ts, client/.kiwi/ko/app.ts, client/.kiwi/ko/index.ts, client/.kiwi/ko/release.ts, client/.kiwi/zh-CN/app.ts, client/.kiwi/zh-CN/index.ts, client/.kiwi/zh-CN/release.ts, client/.kiwi/zh-TW/app.ts, client/.kiwi/zh-TW/index.ts, client/.kiwi/zh-TW/release.ts, client/app/globals.css, client/app/layout.tsx, client/app/page.tsx, client/app/release/page.tsx, client/components/HomeFooter.tsx, client/components/HomeHeader.tsx, client/tailwind.config.js
=> feat: add the page of release notes

client/app/factory/edit/components/BotCreateForm.tsx, client/app/hooks/useBot.ts, client/app/services/BotsController.ts, server/bot/router.py
=> fix: get the GitHub avatar from the api instead of the cache

client/app/market/page.tsx
=> fix: initial request error

client/app/github/installed/page.tsx
=> feat: redireact to the factory after user installed the github app

client/.kiwi/en/edit.ts, client/.kiwi/ja/edit.ts, client/.kiwi/ko/edit.ts, client/.kiwi/zh-CN/edit.ts, client/.kiwi/zh-TW/edit.ts, client/app/factory/edit/page.tsx, client/app/hooks/useUser.ts, client/app/services/UserController.ts, client/app/utils/tools.ts, client/components/User.tsx, server/auth/get_user_info.py, server/auth/router.py
=> feat: add the auto complete for the bot config

server/agent/prompts/issue_helper.py, server/agent/prompts/pull_request.py, server/event_handler/discussion.py, server/event_handler/issue.py, server/event_handler/pull_request.py
=> fix: skip the draft pr task and set fixed replies for specific issues

assistant/src/Chat/index.css
=> fix: style pollution of the Bubble component.

assistant/package.json, assistant/yarn.lock, client/yarn.lock
=> chore: release @petercatai/assistant@2.0.8

client/app/services/TokensController.ts
=> fix: passing withCredentials

assistant/package.json, assistant/src/Chat/components/MarkdownRender.tsx, assistant/src/Chat/index.tsx
By using React.memo to reduce redundant renders, avoid triggering errors caused by reaching React's maximum render limit
=> perf(assistant): optimize message rendering performance using React.memo

assistant/package.json, assistant/src/Chat/components/InputAreaRender.tsx
=> style(assistant): tweak the style of the button

server/bot/list.py, server/bot/router.py
=> fix: solve the page of empty factory list

assistant/README.md, assistant/package.json, assistant/src/Assistant/InitAssistant.tsx, assistant/src/Assistant/index.tsx, assistant/src/index.ts, assistant/tsconfig.json, docs/guides/quick_ assistant_start.md, docs/guides/quick_ assistant_start_cn.md
release @petercatai/assistant@2.0.18
=> fix(Assistant): solve the umd error

server/auth/middleware.py
=> chore: fix whitelist

assistant/package.json, assistant/src/hooks/useUser.ts, server/main.py
Temporarily lift same-site session restrictions to resolve login problems with third-party applications
close #687
=> fix(auth): remove same-site lax restrictions

assistant/package.json, assistant/src/TrendChart/index.md, assistant/src/TrendChart/index.tsx, assistant/src/index.ts, assistant/yarn.lock
=> feat(assistant): add the TrendChart

assistant/package.json, assistant/src/RankChart/index.md, assistant/src/RankChart/index.tsx, assistant/src/TrendChart/index.tsx, assistant/src/index.ts
=> feat(assistant): add the RankChart

assistant/src/RankChart/index.tsx, assistant/src/TrendChart/index.md, assistant/src/TrendChart/index.tsx, server/insight/router.py, server/insight/service/pr.py
=> feat: add the areaChart

assistant/package.json, assistant/src/AreaChart/index.md, assistant/src/AreaChart/index.tsx, assistant/src/BoxChart/index.tsx, assistant/src/Heatmap/index.tsx, assistant/src/LineChart/index.tsx, assistant/src/SegmentedTabs/index.tsx, assistant/src/ThoughtChain/index.tsx, assistant/yarn.lock
* release petercatai/assistant@2.1.0-alpha.0
=> feat(assistant): add the SegmentedTabs and fix the build

server/agent/base.py
=> fix: langchain 0.3 message content format

server/user/router.py
=> fix: remove deepseek
