petercat-ai/petercat

- server/agent/prompts/pull_request.py
- server/bot/builder.py
- server/event_handler/pull_request.py
- move filediff from role prompt to content
- avoid template replacement issue 
```
Single '}' encountered in format string
```
> fix: move diff to content

- client/app/factory/edit/components/Knowledge.tsx
- client/app/factory/edit/page.tsx
- petercat_utils/rag_helper/git_doc_task.py
- pyproject.toml
> fix: solve the issue of task tigger

- petercat_utils/data_class.py
- petercat_utils/rag_helper/git_doc_task.py
- petercat_utils/rag_helper/git_task.py
- petercat_utils/rag_helper/retrieval.py
- petercat_utils/rag_helper/task.py
- pyproject.toml
- server/rag/router.py
> refactor: remove the dependency on bot_id in the task scheduling process

- server/README.zh-CN.md
- server/github_app/router.py
close https://github.com/petercat-ai/petercat/issues/458
> [fix]:fix install repo is id bug

- server/github_app/router.py
issue：https://github.com/petercat-ai/petercat/issues/537
> revert(get_user_repos_installed_app): Rollback the method for obtaining a user's GitHub organization.

- client/.kiwi/en/DeployBotModal.ts
- client/.kiwi/ja/DeployBotModal.ts
- client/.kiwi/ko/DeployBotModal.ts
- client/.kiwi/zh-CN/DeployBotModal.ts
- client/.kiwi/zh-TW/DeployBotModal.ts
- client/app/factory/edit/components/DeployBotModal/DeployContent.tsx
- client/app/factory/edit/components/DeployBotModal/index.tsx
- client/kiwi-config.json
Added a prompt for authorizing the Petercat OAuth for the GitHub organization under the list of repositories for deployable bots.
> feat(deployment): add a prompt for authorizing the github organiztion

- server/core/dao/repositoryConfigDAO.py
- server/event_handler/intsall.py
- server/github_app/handlers.py
- server/github_app/router.py
* 重构GitHub APP 安装逻辑
* 增加 repositoryDAO 批量删除和添加的方法，替代for循环入库
* 增加 InstallationEditEventHandler 响应 Repository access 的编辑逻辑
close #537 
close #566 
TODO: 部署上线验证无误后可以删除 github_app_authorization 表及其类型定义和引用
> refactor(install): Refactor GitHub App Installation Logic

- client/app/hooks/useBot.ts
- server/auth/router.py
- server/bot/router.py
- server/core/dao/repositoryConfigDAO.py
- server/github_app/utils.py
* 允许同一个GitHub组织成员编辑所有改组织下已经安装过的机器人
* 修复市场空间机器人检索结果不准确问题
> feat: enable collaboration for the same git org

- server/agent/prompts/issue_helper.py
- server/agent/prompts/pull_request.py
参考 https://github.com/afc163/fanyi/pull/155#issuecomment-2487018221 把内容放在折叠区域内。
> style: put further assistance text in <details>

- client/app/factory/list/components/BotCard.tsx
- migrations/supabase/migrations/20241218093541_remote_schema.sql
- server/bot/list.py
- server/bot/router.py
* 重构 bots 查询接口，将空间机器人需要的多张表信息一次返回，减少空间页面额外的循环请求
> refactor: merge bot list query requests

- server/agent/prompts/pull_request.py
- server/event_handler/discussion.py
- server/event_handler/issue.py
- server/event_handler/pull_request.py
- server/utils/fuzzy_match.py
> feat: add skip key words for the pull request handler and  issue handler

- server/auth/clients/auth0.py
- server/auth/clients/base.py
- server/auth/clients/local.py
- server/auth/router.py
> fix: logout logic

- server/auth/router.py
- server/core/dao/profilesDAO.py
> fix: new user auth

- assistant/src/Assistant/index.tsx
- server/agent/prompts/bot_template.py
> fix: solve the icon color for the assitant

- .github/workflows/aws-preview.yml
- .github/workflows/aws-prod.yml
- client/.kiwi/en/components.ts
- client/.kiwi/ja/components.ts
- client/.kiwi/ko/components.ts
- client/.kiwi/zh-CN/components.ts
- client/.kiwi/zh-TW/components.ts
- client/app/hooks/useToken.ts
- client/app/services/TokensController.ts
- client/app/user/tokens/components/CreateModal.tsx
- server/agent/llm/clients/deepseek.py
- server/core/service/user_token_usage.py
- template.yml
> feat: impl deepseek

- server/agent/base.py
- server/agent/prompts/pull_request.py
- server/agent/tools/pull_request.py
> fix: skip cr task if there is no error

- server/agent/prompts/pull_request.py
- server/agent/tools/pull_request.py
- server/core/models/bot.py
> fix: add the function to check if the pr summary is correct and fix it

- client/next.config.js
If output: "standalone" is not included in module.exports, the standalone folder will not be generated successfully.
> fix: enable standalone output in Next.js configuration

- server/insight/router.py
- server/insight/service/issue.py
- server/insight/service/pr.py
- server/main.py
- server/tests/utils/test_insight.py
- server/utils/insight.py
api ref: https://open-digger.cn/en/docs/user_docs/metrics/metrics_usage_guide
> feat: add API for data insights on PRs, issues, and code changes.

- server/bot/builder.py
- server/rag/router.py
- server/requirements.txt
> feat(rag): add api /retrieval/bot
